#!/bin/bash

protected_branch='main'
current_branch=$(git rev-parse --abbrev-ref HEAD | sed -e 's,.*/\(.*\),\1,')

if [ $protected_branch = $current_branch ]
then
  echo "Push main is not allowed"
  exit 1 # push will not execute
else
  exit 0 # push will execute
fi
